# Source this file to setup environment variables
IXIA_HOME=/opt/Ixia/ixos
TCL_LIBRARY=$IXIA_HOME/lib/tcl8.5

LD_LIBRARY_PATH=$IXIA_HOME/lib:$IxiaLibPath:$TclLibPath:$LD_LIBRARY_PATH
#IXIA_TCL_DIR=$IXIA_HOME/lib
IXIA_TCL_DIR=/usr/lib64/tcl8.5
TCLLIBPATH="$LOCAL_TCLLIBPATH $IXIA_HOME/lib"
IXIA_SAMPLES=$IXIA_HOME/lib/ixTcl1.0
IXIA_VERSION=6.50
PATH=$IXIA_HOME/bin:$PATH
export TCLLIBPATH IXIA_HOME TCL_LIBRARY LD_LIBRARY_PATH
export IXIA_SAMPLES IXIA_TCL_DIR IXIA_VERSION PATH

