- name: User SSH public key playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Set authorized keys
      authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      when: inventory_hostname != 'localhost'
