#!/bin/bash
      
rc=0

if [ "$1" == "" ] ; then

      echo ""
      echo "  /"
      echo "    Targets:"
      echo "        SP"
      echo "        SYS"
      echo ""
      echo "    Properties:"
      echo ""
      echo "    Target Commands:"
      echo "        show"
      echo "        cd"
      echo ""
      echo ""

elif [ "$1" == "reset" -a "$2" == "/SYS" ] ; then

      echo ""
      echo "SYS Power Reset"
      echo "/SYS reset"
      echo ""

elif [ "$1" == "/SYS/powerSupply" ] ; then

      echo ""
      echo "    Properties:"
      echo "        PSU Redundancy = N/A "
      echo "        PSU1 Status = Presence Detected, "
      echo "        PSU2 Status = All Deasserted "
      echo ""
      echo ""

elif [ "$1" == "/SYS/voltage" ] ; then

      echo ""
      echo "    Properties:"
      echo "        Volt_VR_CPU0 = ok"
      echo "        Volt_VR_CPU1 = ok"
      echo "        Volt_P5V = ok"
      echo "        Volt_P5V_AUX = ok"
      echo "        Volt_P3V3 = ok"
      echo "        Volt_P1V05 = ok"
      echo "        Volt_P1V8_AUX = ok"
      echo "        Volt_P12V = ok"
      echo "        Volt_P3V3_AUX = ok"
      echo "        Volt_VR_DIMM_AB = ok"
      echo "        Volt_VR_DIMM_CD = ok"
      echo "        Volt_VR_DIMM_EF = ok"
      echo "        Volt_VR_DIMM_GH = ok"
      echo "        Volt_P3V_BAT = ok"
      echo ""
      echo ""

elif [ "$1" == "/SYS/fan" ] ; then

      echo ""
      echo "    Properties:"
      echo "        Fan_SYS0_1 = ok"
      echo "        Fan_SYS0_2 = ok"
      echo "        Fan_SYS1_1 = ok"
      echo "        Fan_SYS1_2 = ok"
      echo "        Fan_SYS2_1 = ok"
      echo "        Fan_SYS2_2 = ok"
      echo "        Fan_SYS3_1 = ok"
      echo "        Fan_SYS3_2 = ok"
      echo "        Fan_SYS4_1 = ok"
      echo "        Fan_SYS4_2 = ok"
      echo "        Fan_SYS5_1 = ok"
      echo "        Fan_SYS5_2 = ok"
      echo "        Fan_PSU1 = ok"
      echo "        Fan_PSU2 = ok"
      echo ""
      echo ""


elif [ "$1" == "/SYS/temperature" ] ; then

      echo ""
      echo "    Properties:"
      echo "        PCH Thermal Trip = major"
      echo "        Temp_CPU0 = major"
      echo "        Temp_CPU1 = major"
      echo "        Temp_DIMM_AB = major"
      echo "        Temp_DIMM_CD = major"
      echo "        Temp_DIMM_EF = major"
      echo "        Temp_DIMM_GH = major"
      echo "        Temp_VR_CPU0 = major"
      echo "        Temp_VR_CPU1 = major"
      echo "        Temp_VR_DIMM_AB = major"
      echo "        Temp_VR_DIMM_CD = major"
      echo "        Temp_VR_DIMM_EF = major"
      echo "        Temp_VR_DIMM_GH = major"
      echo "        Temp_Ambient_FP = major"
      echo "        Temp_PCI_Area = major"
      echo "        Temp_PCI_Inlet1 = major"
      echo "        Temp_PCI_Inlet2 = major"
      echo "        Temp_PCH = major"
      echo "        Temp_Outlet = major"
      echo "        MB Thermal Trip = major"
      echo "        Temp_HBA_LSI = major"
      echo "        Temp_OCP = na     "
      echo "        Temp_PSU1 = major"
      echo "        Temp_PSU2 = major"
      echo ""
      echo ""

else

     echo "Invalid command 'emulated' - type 'help' for a list of commands."
     rc=1
fi

exit $rc

