apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: default
spec:
  containers:
  - image: tis-lab-registry.cumulus.wrs.com:9001/pv-test
    command: ["/bin/sh","-c"]
    args: ["sleep 60m"]
    imagePullPolicy: IfNotPresent
    name: client-container
  restartPolicy: Always