CLI_TIMEOUT = 600


class HostTimeout:
    ONLINE_AFTER_LOCK = 1200
    COMPUTE_UNLOCK = 840
    CONTROLLER_UNLOCK = 1360
    REBOOT = 2000
    SWACT = 180
    LOCK = 900
    TASK_CLEAR = 300
    FAIL_AFTER_REBOOT = 120
    HYPERVISOR_UP_AFTER_AVAIL = 180
    COMPUTE_LOCK = 30
    UPGRADE = 7200
    WIPE_DISK_TIMEOUT = 30
    PING_TIMEOUT = 60
    TIMEOUT_BUFFER = 2


class VMTimeout:
    STATUS_CHANGE = 120
    STATUS_VERIFY_RESIZE = 30
    LIVE_MIGRATE_COMPLETE = 120
    COLD_MIGRATE_CONFIRM = 600
    BOOT_VM = 600
    DELETE = 180
    VOL_ATTACH = 60
    SSH_LOGIN = 20
    AUTO_RECOVERY = 600
    REBOOT = 180
    PAUSE = 180
    IF_ADD = 30
    REBUILD = 300
    DHCP_IP_ASSIGN = 30


class VolumeTimeout:
    STATUS_CHANGE = 720
    DELETE = 60


class SysInvTimeout:
    RETENTION_PERIOD_SAVED = 30
    RETENTION_PERIOD_MODIFY = 60
    DNS_SERVERS_SAVED = 30
    DNS_MODIFY = 60


class CMDTimeout:
    HOST_CPU_MODIFY = 600
    RESOURCE_LIST = 60
    REBOOT_VM = 60
    CPU_PROFILE_APPLY = 30


class ImageTimeout:
    CREATE = 600
    STATUS_CHANGE = 30
    DELETE = 120


class EventLogTimeout:
    HEARTBEAT_ESTABLISH = 300
    HEALTH_CHECK_FAIL = 60
    VM_REBOOT_EVENT = 60
    NET_AGENT_NOT_RESPOND_CLEAR = 120


class MTCTimeout:
    KILL_PROCESS_HOST_CHANGE_STATUS = 40
    KILL_PROCESS_HOST_KEEP_STATUS = 20
    KILL_PROCESS_SWACT_NOT_START = 20
    KILL_PROCESS_SWACT_START = 40
    KILL_PROCESS_SWACT_COMPLETE = 40


class CeilTimeout:
    EXPIRE = 300


class OrchestrationPhaseTimeout:
        INITIAL = 20
        BUILD = 60
        ABORT = 7200
        APPLY = 7200
