# This rule opens up default HTTPS port 443
# It is required to access openstack Horizon via FQDN
# To apply use:
# kubectl apply -f openstack-gnp-oam.yaml
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: gnp-oam-overrides
spec:
  ingress:
  - action: Allow
    destination:
      ports:
      - 443 
    protocol: TCP
  order: 500
  selector: has(iftype) && iftype == 'oam'
  types:
  - Ingress

